import type { Metadata } from "next";
import { auth } from "@clerk/nextjs/server";
import { ClerkProvider } from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import { ConditionalHeader } from "@/components/layout";
import { getUserDisplayInfo } from "@/lib/get-user-display-info";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { userId, sessionClaims } = await auth();
  const role = (sessionClaims?.metadata as { role?: string } | undefined)?.role;
  const displayInfo =
    userId != null ? await getUserDisplayInfo() : { displayName: null, username: null, imageUrl: null };

  return (
    <ClerkProvider
      appearance={{
        variables: {
          colorPrimary: '#00c8ff',
          colorBackground: '#0a1223',
          colorInputBackground: '#0a1223',
          colorInputText: '#c8dff0',
          colorText: '#c8dff0',
          colorTextSecondary: '#4a6080',
          borderRadius: '10px',
        },
        layout: {
          unsafe_disableDevelopmentModeWarnings: true,
        },
        elements: {
          card: 'shadow-xl border border-[rgba(0,200,255,0.18)]',
          cardBox: 'bg-[#0a1223]',
          headerTitle: 'text-[#e8f4ff]',
          headerSubtitle: 'text-[#4a6080]',
          formFieldLabel: 'text-[#4a6080]',
          formFieldInput: 'bg-[rgba(0,200,255,0.05)] border-[rgba(0,200,255,0.18)] text-[#c8dff0]',
          footerActionLink: 'text-[#00c8ff]',
          navbarButton: 'text-[#c8dff0]',
          userButtonPopoverCard: 'bg-[#0a1223] border border-[rgba(0,200,255,0.18)] shadow-xl',
          userButtonPopoverActionButton: 'text-white hover:bg-[rgba(0,200,255,0.08)] hover:text-[#00c8ff]',
          userButtonPopoverFooter: 'hidden',
        },
      }}
    >
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <ConditionalHeader
            displayName={displayInfo.displayName}
            username={displayInfo.username}
            role={role}
          />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
